// Mock data cho section Kiến thức và Tin tức

export interface Article {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  categorySlug: string;
  author: string;
  date: string;
  readTime: string;
  image: string;
  featured?: boolean;
  tags?: string[];
}

export interface Category {
  slug: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  articleCount: number;
}

export interface VideoItem {
  id: number;
  slug: string;
  title: string;
  description: string;
  duration: string;
  thumbnail: string;
  date: string;
  views: string;
  category: string;
  tags?: string[];
}

export interface PodcastItem {
  id: number;
  slug: string;
  title: string;
  description: string;
  duration: string;
  episode: number;
  date: string;
  guests?: string;
  category: string;
  tags?: string[];
}

export interface WebinarItem {
  id: number;
  slug: string;
  title: string;
  description: string;
  date: string;
  time: string;
  duration: string;
  speaker: string;
  status: "upcoming" | "recorded";
  registrationUrl?: string;
  category: string;
  tags?: string[];
}

export interface FAQItem {
  id: number;
  question: string;
  answer: string;
  group: string;
}

export interface ReportItem {
  id: number;
  title: string;
  description: string;
  fileType: string;
  fileSize: string;
  date: string;
  category: string;
  fileUrl: string;
}

export interface RegionItem {
  id: number;
  name: string;
  code: string;
  area: string;
  population: string;
  planningStatus: "Đã phê duyệt" | "Đang lập" | "Chờ duyệt";
  highlights: string[];
  lastUpdate: string;
  keyProjects: number;
}

// Danh mục kiến thức
export const CATEGORIES: Category[] = [
  {
    slug: "thi-truong",
    name: "Góc nhìn thị trường",
    description: "Phân tích thị trường, xu hướng và thông tin đầu tư",
    icon: "TrendingUp",
    color: "from-red-500 to-orange-500",
    articleCount: 24,
  },
  {
    slug: "nghien-cuu-bao-cao",
    name: "Nghiên cứu và Báo cáo",
    description: "Nghiên cứu chuyên đề, báo cáo và tài liệu tải xuống",
    icon: "FileBarChart",
    color: "from-blue-500 to-cyan-500",
    articleCount: 18,
  },
  {
    slug: "quy-hoach",
    name: "Tin và phân tích quy hoạch",
    description: "Tin tức, phân tích quy hoạch và dữ liệu khu vực BĐS",
    icon: "Map",
    color: "from-green-500 to-emerald-500",
    articleCount: 5,
  },
  {
    slug: "phap-ly",
    name: "Pháp lý",
    description: "Chính sách, quy định và phân tích pháp lý bất động sản",
    icon: "Scale",
    color: "from-purple-500 to-indigo-500",
    articleCount: 5,
  },
  {
    slug: "dau-tu",
    name: "Đầu tư",
    description: "Phân tích đầu tư, tài chính dự án, M&A và gọi vốn",
    icon: "Briefcase",
    color: "from-amber-500 to-yellow-500",
    articleCount: 10,
  },
  {
    slug: "tham-dinh-gia-tai-chinh",
    name: "Thẩm định giá - Tài chính",
    description: "Kiến thức thẩm định giá, tài chính và định giá",
    icon: "Calculator",
    color: "from-teal-500 to-cyan-600",
    articleCount: 8,
  },
  {
    slug: "quan-ly-van-hanh",
    name: "Quản lý và Vận hành",
    description: "Quản lý tòa nhà, quản lý tài sản, Facility & Operation",
    icon: "Settings",
    color: "from-slate-500 to-gray-600",
    articleCount: 11,
  },
  {
    slug: "kien-truc-xay-dung",
    name: "Kiến trúc - Xây dựng",
    description: "Thiết kế, thi công và cải tạo công trình",
    icon: "Building2",
    color: "from-rose-500 to-pink-600",
    articleCount: 11,
  },
  {
    slug: "hoat-dong-kepler",
    name: "Hoạt động Kepler",
    description: "Tin doanh nghiệp, sự kiện và hoạt động nội bộ",
    icon: "Users",
    color: "from-red-600 to-red-800",
    articleCount: 11,
  },
];

// Bài viết mock
export const ARTICLES: Article[] = [
  {
    id: 1,
    slug: "xu-huong-thi-truong-bds-2025",
    title: "Xu hướng thị trường bất động sản 2025: Khối phục hồi và cơ hội mới",
    excerpt: "Thị trường BĐS dự kiến phục hồi mạnh trong năm 2025 với nhiều cơ hội đầu tư từ khu vực công nghiệp và nhà ở xã hội.",
    category: "Góc nhìn thị trường",
    categorySlug: "thi-truong",
    author: "Nguyễn Văn A",
    date: "2025-01-15",
    readTime: "8 phút",
    image: "/seo.png",
    featured: true,
    tags: ["thị trường", "bất động sản", "2025"],
  },
  {
    id: 2,
    slug: "phan-tich-quy-hoach-tp-hcm-2025",
    title: "Phân tích quy hoạch TP.HCM 2025: Những khu vực tiềm năng",
    excerpt: "Đánh giá chi tiết các thay đổi quy hoạch tại TP.HCM và cơ hội đầu tư cho nhà phát triển dự án.",
    category: "Quy hoạch",
    categorySlug: "quy-hoach",
    author: "Trần Thị B",
    date: "2025-01-12",
    readTime: "12 phút",
    image: "/seo.png",
    featured: true,
    tags: ["quy hoạch", "TP.HCM"],
  },
  {
    id: 3,
    slug: "tham-dinh-gia-bds-thuong-mai",
    title: "Thẩm định giá BĐS thương mại",
    excerpt: "Các phương pháp thẩm định giá phổ biến và ứng dụng thực tế tại Việt Nam.",
    category: "Thẩm định giá - Tài chính",
    categorySlug: "tham-dinh-gia-tai-chinh",
    author: "Lê Văn C",
    date: "2025-01-10",
    readTime: "15 phút",
    image: "/seo.png",
    tags: ["thẩm định giá", "BĐS thương mại", "kiến thức thẩm định giá"],
  },
  {
    id: 4,
    slug: "chinh-sach-phap-ly-bds-moi-nhat",
    title: "Cập nhật chính sách pháp lý BĐS: Những điểm mới quan trọng",
    excerpt: "Tổng hợp các thay đổi pháp lý gần đây ảnh hưởng đến thị trường BĐS và nhà đầu tư.",
    category: "Pháp lý",
    categorySlug: "phap-ly",
    author: "Phạm Thị D",
    date: "2025-01-08",
    readTime: "10 phút",
    image: "/seo.png",
    tags: ["pháp lý", "chính sách"],
  },
  {
    id: 5,
    slug: "co-hoi-dau-tu-bds-cong-nghiep",
    title: "Cơ hội đầu tư BĐS công nghiệp 2025",
    excerpt: "Khu vực BĐS công nghiệp đang trở thành điểm sáng với nhu cầu cho thuê tăng mạnh từ FDI.",
    category: "Đầu tư",
    categorySlug: "dau-tu",
    author: "Hoàng Văn E",
    date: "2025-01-05",
    readTime: "7 phút",
    image: "/seo.png",
    tags: ["đầu tư", "BĐS công nghiệp", "phân tích đầu tư"],
  },
  {
    id: 9,
    slug: "bao-cao-thi-truong-bds-q4-2024",
    title: "Báo cáo thị trường BĐS Quý 4/2024: Tổng kết và dự báo",
    excerpt: "Báo cáo chi tiết về diễn biến thị trường BĐS quý 4/2024 và dự báo cho năm 2025.",
    category: "Nghiên cứu và Báo cáo",
    categorySlug: "nghien-cuu-bao-cao",
    author: "Phòng nghiên cứu",
    date: "2024-12-20",
    readTime: "20 phút",
    image: "/seo.png",
    tags: ["báo cáo", "quý 4", "2024"],
  },
  {
    id: 10,
    slug: "ma-trong-bds-co-hoi-va-thach-thuc",
    title: "M&A trong BĐS: Cơ hội và thách thức cho nhà đầu tư",
    excerpt: "Phân tích các giao dịch M&A nổi bật trong ngành BĐS và cơ hội cho nhà đầu tư năm 2025.",
    category: "Đầu tư",
    categorySlug: "dau-tu",
    author: "Nguyễn Văn A",
    date: "2024-12-18",
    readTime: "11 phút",
    image: "/seo.png",
    tags: ["m&a và gọi vốn"],
  },
  {
    id: 11,
    slug: "xu-huong-thi-truong-can-ho-2025",
    title: "Xu hướng thị trường căn hộ 2025: Nhu cầu thực và dư cung",
    excerpt: "Phân tích chi tiết cung cầu thị trường căn hộ tại các thành phố lớn trong năm 2025.",
    category: "Góc nhìn thị trường",
    categorySlug: "thi-truong",
    author: "Trần Thị B",
    date: "2024-12-15",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["căn hộ", "thị trường"],
  },
  {
    id: 12,
    slug: "quy-dinh-phap-ly-cho-thue-dat-nong-nghiep",
    title: "Quy định pháp lý mới về cho thuê đất nông nghiệp",
    excerpt: "Tổng hợp các quy định pháp lý mới về cho thuê đất nông nghiệp và lưu ý cho nhà đầu tư.",
    category: "Pháp lý",
    categorySlug: "phap-ly",
    author: "Phạm Thị D",
    date: "2024-12-10",
    readTime: "7 phút",
    image: "/seo.png",
    tags: ["pháp lý", "quy định", "đất nông nghiệp"],
  },
  {
    id: 13,
    slug: "quy-hoach-ha-tang-giao-thong-tp-hcm",
    title: "Quy hoạch hạ tầng giao thông TP.HCM đến 2030: Động lực mới cho BĐS",
    excerpt: "Tổng quan các dự án hạ tầng giao thông trọng điểm tại TP.HCM và tác động đến giá trị BĐS khu vực.",
    category: "Tin và phân tích quy hoạch",
    categorySlug: "quy-hoach",
    author: "Trần Thị B",
    date: "2025-01-20",
    readTime: "10 phút",
    image: "/seo.png",
    featured: true,
    tags: ["quy hoạch", "TP.HCM", "hạ tầng"],
  },
  {
    id: 14,
    slug: "quy-hoach-vung-ha-noi-2030",
    title: "Quy hoạch vùng Hà Nội 2030: Định hướng không gian và cơ hội đầu tư",
    excerpt: "Phân tích định hướng không gian vùng thủ đô theo quy hoạch mới và các khu vực nổi bật.",
    category: "Tin và phân tích quy hoạch",
    categorySlug: "quy-hoach",
    author: "Nguyễn Văn A",
    date: "2025-01-18",
    readTime: "11 phút",
    image: "/seo.png",
    tags: ["quy hoạch", "Hà Nội", "vùng"],
  },
  {
    id: 15,
    slug: "quy-hoach-khu-do-thi-moi-binh-duong",
    title: "Quy hoạch khu đô thị mới Bình Dương: Mô hình phát triển bền vững",
    excerpt: "Đánh giá mô hình quy hoạch đô thị thông minh tại Bình Dương và tiềm năng BĐS công nghiệp.",
    category: "Tin và phân tích quy hoạch",
    categorySlug: "quy-hoach",
    author: "Hoàng Văn E",
    date: "2025-01-16",
    readTime: "9 phút",
    image: "/seo.png",
    tags: ["quy hoạch", "Bình Dương", "đô thị mới"],
  },
  {
    id: 16,
    slug: "quy-hoach-da-nang-2030-huong-toi-thanh-pho-thong-minh",
    title: "Quy hoạch Đà Nẵng 2030: Hướng tới thành phố thông minh và xanh",
    excerpt: "Phân tích định hướng phát triển Đà Nẵng theo hướng đô thị thông minh, sinh thái và du lịch.",
    category: "Tin và phân tích quy hoạch",
    categorySlug: "quy-hoach",
    author: "Lê Văn C",
    date: "2025-01-14",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["quy hoạch", "Đà Nẵng", "thông minh"],
  },
  {
    id: 17,
    slug: "phan-tich-tranh-chap-so-huu-bds",
    title: "Phân tích tranh chấp sở hữu BĐS: Rủi ro và giải pháp",
    excerpt: "Đánh giá các nguy cơ pháp lý trong tranh chấp sở hữu bất động sản và cách phòng ngừa.",
    category: "Pháp lý",
    categorySlug: "phap-ly",
    author: "Phạm Thị D",
    date: "2025-01-07",
    readTime: "11 phút",
    image: "/seo.png",
    featured: true,
    tags: ["pháp lý", "phân tích", "tranh chấp", "sở hữu"],
  },
  {
    id: 18,
    slug: "quy-dinh-ve-cap-so-do-cho-cong-trinh-xay-dung",
    title: "Quy định về cấp Sổ đỏ cho công trình xây dựng mới",
    excerpt: "Tổng hợp quy định, điều kiện và thủ tục cấp Giấy chứng nhận quyền sử dụng đất cho công trình xây dựng.",
    category: "Pháp lý",
    categorySlug: "phap-ly",
    author: "Nguyễn Văn A",
    date: "2025-01-06",
    readTime: "9 phút",
    image: "/seo.png",
    tags: ["pháp lý", "sổ đỏ", "quy định"],
  },
  {
    id: 19,
    slug: "chinh-sach-thue-dat-cong-nghiep-2025",
    title: "Chính sách thuế đất công nghiệp 2025: Ưu đãi và lưu ý",
    excerpt: "Phân tích chính sách thuế đất đối với khu công nghiệp, khu chế xuất và doanh nghiệp thuê đất.",
    category: "Pháp lý",
    categorySlug: "phap-ly",
    author: "Trần Thị B",
    date: "2025-01-05",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["pháp lý", "chính sách", "thuế đất"],
  },
  {
    id: 20,
    slug: "phan-tich-rui-ro-mua-nha-chung-cu-cu",
    title: "Phân tích rủi ro pháp lý khi mua chung cư cũ",
    excerpt: "Đánh giá các rủi ro pháp lý thường gặp khi giao dịch chung cư đã qua sử dụng và cách kiểm soát trước khi ký hợp đồng.",
    category: "Pháp lý",
    categorySlug: "phap-ly",
    author: "Lê Văn C",
    date: "2025-01-04",
    readTime: "10 phút",
    image: "/seo.png",
    tags: ["pháp lý", "phân tích", "chung cư cũ"],
  },
  {
    id: 21,
    slug: "nguoi-viet-dinh-cu-nuoc-ngoai-quyen-su-dung-dat",
    title: "Người Việt định cư nước ngoài có được cấp quyền sử dụng đất?",
    excerpt: "Phân tích pháp lý về quyền sở hữu, quyền sử dụng đất của cá nhân Việt Nam định cư ở nước ngoài.",
    category: "Pháp lý",
    categorySlug: "phap-ly",
    author: "Phạm Thị D",
    date: "2025-01-03",
    readTime: "9 phút",
    image: "/seo.png",
    tags: ["pháp lý", "phân tích", "người Việt ở nước ngoài"],
  },
  {
    id: 22,
    slug: "chuyen-nhuong-du-an-bds-theo-luat-kinh-doanh-bds",
    title: "Điều kiện chuyển nhượng dự án BĐS theo Luật Kinh doanh BĐS",
    excerpt: "Phân tích các điều kiện, hồ sơ và quy trình chuyển nhượng toàn bộ dự án đầu tư xây dựng nhà ở để bán.",
    category: "Pháp lý",
    categorySlug: "phap-ly",
    author: "Nguyễn Văn A",
    date: "2025-01-02",
    readTime: "12 phút",
    image: "/seo.png",
    tags: ["pháp lý", "phân tích", "chuyển nhượng dự án"],
  },
  {
    id: 23,
    slug: "cau-truc-tai-chinh-du-an-bds",
    title: "Cấu trúc tài chính dự án BĐS: Vốn vay, vốn chủ sở hữu và IRR",
    excerpt: "Phân tích cấu trúc vốn, dòng tiền và chỉ số IRR trong các dự án bất động sản quy mô trung và lớn.",
    category: "Đầu tư",
    categorySlug: "dau-tu",
    author: "Lê Văn C",
    date: "2025-01-18",
    readTime: "10 phút",
    image: "/seo.png",
    tags: ["đầu tư", "tài chính dự án"],
  },
  {
    id: 24,
    slug: "phan-tich-rui-ro-dau-tu-can-ho-cho-thue",
    title: "Phân tích rủi ro dòng tiền khi đầu tư căn hộ cho thuê",
    excerpt: "Đánh giá rủi ro lấp đầy, chi phí vận hành và biến động giá thuê đối với mô hình đầu tư căn hộ cho thuê.",
    category: "Đầu tư",
    categorySlug: "dau-tu",
    author: "Trần Thị B",
    date: "2025-01-17",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["đầu tư", "phân tích đầu tư", "căn hộ cho thuê"],
  },
  {
    id: 25,
    slug: "phan-tich-xu-huong-dau-tu-bds-2025",
    title: "Phân tích xu hướng đầu tư bất động sản năm 2025",
    excerpt: "Các phân khúc tiềm năng, dòng vốn ngoại và yếu tố vĩ mô tác động đến quyết định đầu tư.",
    category: "Đầu tư",
    categorySlug: "dau-tu",
    author: "Nguyễn Văn A",
    date: "2025-01-25",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["phân tích đầu tư"],
  },
  {
    id: 26,
    slug: "danh-gia-rui-ro-dau-tu-can-ho-cao-cap",
    title: "Đánh giá rủi ro khi đầu tư căn hộ cao cấp tại các đô thị lớn",
    excerpt: "Phân tích chi tiết về thanh khoản, pháp lý và biến động giá của phân khúc căn hộ hạng sang.",
    category: "Đầu tư",
    categorySlug: "dau-tu",
    author: "Trần Thị B",
    date: "2025-01-22",
    readTime: "6 phút",
    image: "/seo.png",
    tags: ["phân tích đầu tư"],
  },
  {
    id: 27,
    slug: "mo-hinh-tai-chinh-du-an-bds",
    title: "Mô hình tài chính dự án bất động sản: Từ feasibility đến IRR",
    excerpt: "Hướng dẫn xây dựng mô hình tài chính, các chỉ số quan trọng và cách đọc báo cáo hiệu quả đầu tư.",
    category: "Đầu tư",
    categorySlug: "dau-tu",
    author: "Lê Văn C",
    date: "2025-01-20",
    readTime: "11 phút",
    image: "/seo.png",
    tags: ["tài chính dự án"],
  },
  {
    id: 28,
    slug: "cau-truc-von-va-dong-tien-du-an",
    title: "Cấu trúc vốn và quản lý dòng tiền trong dự án bất động sản",
    excerpt: "Tối ưu tỷ lệ nợ/vốn chủ, lịch giải ngân và các kịch bản stress-test dòng tiền.",
    category: "Đầu tư",
    categorySlug: "dau-tu",
    author: "Phạm Thị D",
    date: "2025-01-19",
    readTime: "9 phút",
    image: "/seo.png",
    tags: ["tài chính dự án"],
  },
  {
    id: 29,
    slug: "chien-luoc-ma-trong-bat-dong-san",
    title: "Chiến lược M&A trong lĩnh vực bất động sản: Cơ hội và bẫy",
    excerpt: "Phân tích các thương vụ M&A điển hình, định giá và những rủi ro thường bị bỏ qua.",
    category: "Đầu tư",
    categorySlug: "dau-tu",
    author: "Hoàng Văn E",
    date: "2025-01-16",
    readTime: "10 phút",
    image: "/seo.png",
    tags: ["m&a và gọi vốn"],
  },
  {
    id: 30,
    slug: "cac-hinh-thuc-goi-von-cho-du-an-bds",
    title: "Các hình thức gọi vốn phổ biến cho dự án bất động sản hiện nay",
    excerpt: "Từ ngân hàng, quỹ đầu tư đến trái phiếu và joint-venture – ưu nhược điểm từng kênh.",
    category: "Đầu tư",
    categorySlug: "dau-tu",
    author: "Vũ Thị F",
    date: "2025-01-15",
    readTime: "7 phút",
    image: "/seo.png",
    tags: ["m&a và gọi vốn"],
  },
  {
    id: 31,
    slug: "phuong-phap-tham-dinh-gia-so-sanh",
    title: "Phương pháp thẩm định giá so sánh: Khi nào và áp dụng thế nào",
    excerpt: "Hướng dẫn áp dụng phương pháp so sánh trực tiếp trong thẩm định giá BĐS và những lưu ý về nguồn dữ liệu.",
    category: "Thẩm định giá - Tài chính",
    categorySlug: "tham-dinh-gia-tai-chinh",
    author: "Lê Văn C",
    date: "2025-01-26",
    readTime: "9 phút",
    image: "/seo.png",
    tags: ["kiến thức thẩm định giá"],
  },
  {
    id: 32,
    slug: "tham-dinh-gia-theo-thu-nhap",
    title: "Thẩm định giá theo phương pháp thu nhập: DCF và capitalization rate",
    excerpt: "Phân tích mô hình chiết khấu dòng tiền và tỷ suất vốn hóa trong định giá BĐS sinh lời.",
    category: "Thẩm định giá - Tài chính",
    categorySlug: "tham-dinh-gia-tai-chinh",
    author: "Trần Thị B",
    date: "2025-01-24",
    readTime: "11 phút",
    image: "/seo.png",
    tags: ["kiến thức thẩm định giá"],
  },
  {
    id: 33,
    slug: "tham-dinh-gia-bds-cong-nghiep",
    title: "Đặc thù thẩm định giá BĐS công nghiệp và kho bãi",
    excerpt: "Các yếu tố đặc thù ảnh hưởng đến giá trị BĐS công nghiệp: vị trí, hạ tầng, hợp đồng thuê dài hạn.",
    category: "Thẩm định giá - Tài chính",
    categorySlug: "tham-dinh-gia-tai-chinh",
    author: "Phạm Thị D",
    date: "2025-01-23",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["kiến thức thẩm định giá"],
  },
  {
    id: 34,
    slug: "dinh-gia-doanh-nghiep-bds",
    title: "Định giá doanh nghiệp BĐS: Từ NAV đến EV",
    excerpt: "Các phương pháp định giá doanh nghiệp hoạt động trong lĩnh vực bất động sản và sai số thường gặp.",
    category: "Thẩm định giá - Tài chính",
    categorySlug: "tham-dinh-gia-tai-chinh",
    author: "Nguyễn Văn A",
    date: "2025-01-22",
    readTime: "12 phút",
    image: "/seo.png",
    tags: ["tài chính và định giá"],
  },
  {
    id: 35,
    slug: "phan-tich-tai-chinh-doanh-nghiep-bds",
    title: "Phân tích tài chính doanh nghiệp BĐS: Chỉ số cần theo dõi",
    excerpt: "Các chỉ số tài chính quan trọng khi đánh giá doanh nghiệp BĐS: biên lợi nhuận, ROE, vòng quay hàng tồn kho.",
    category: "Thẩm định giá - Tài chính",
    categorySlug: "tham-dinh-gia-tai-chinh",
    author: "Hoàng Văn E",
    date: "2025-01-21",
    readTime: "10 phút",
    image: "/seo.png",
    tags: ["tài chính và định giá"],
  },
  {
    id: 36,
    slug: "mo-hinh-dinh-gia-dcf-cho-du-an",
    title: "Mô hình DCF cho dự án BĐS: Xây dựng và kiểm soát giả định",
    excerpt: "Hướng dẫn xây dựng mô hình chiết khấu dòng tiền cho dự án BĐS và các giả định cần kiểm chứng.",
    category: "Thẩm định giá - Tài chính",
    categorySlug: "tham-dinh-gia-tai-chinh",
    author: "Lê Văn C",
    date: "2025-01-20",
    readTime: "13 phút",
    image: "/seo.png",
    tags: ["tài chính và định giá"],
  },
  {
    id: 37,
    slug: "dinh-gia-dat-nen-dau-tu",
    title: "Định giá đất nền đầu tư: Những sai lầm phổ biến",
    excerpt: "Các sai lầm thường gặp khi định giá đất nền và cách nhận diện giá trị thực so với giá thị trường.",
    category: "Thẩm định giá - Tài chính",
    categorySlug: "tham-dinh-gia-tai-chinh",
    author: "Vũ Thị F",
    date: "2025-01-19",
    readTime: "7 phút",
    image: "/seo.png",
    tags: ["kiến thức thẩm định giá"],
  },
  // ===== Quản lý và Vận hành — Quản lý tòa nhà =====
  {
    id: 38,
    slug: "quan-ly-toa-nha-thong-minh",
    title: "Quản lý tòa nhà thông minh: Xu hướng và giải pháp",
    excerpt: "Ứng dụng công nghệ IoT trong quản lý vận hành tòa nhà, tối ưu chi phí và nâng cao trải nghiệm.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Vũ Thị F",
    date: "2025-01-03",
    readTime: "9 phút",
    image: "/seo.png",
    featured: true,
    tags: ["quản lý tòa nhà", "IoT"],
  },
  {
    id: 39,
    slug: "tiep-nhan-ban-giao-toa-nha-moi",
    title: "Quy trình tiếp nhận & bàn giao tòa nhà mới: Checklist chuẩn",
    excerpt: "Bộ checklist chi tiết từ kỹ thuật, pháp lý đến vận hành khi tiếp nhận một tòa nhà mới đưa vào sử dụng.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Trần Thị B",
    date: "2025-02-08",
    readTime: "11 phút",
    image: "/seo.png",
    tags: ["quản lý tòa nhà", "bàn giao"],
  },
  {
    id: 40,
    slug: "bao-tri-toa-nha-de-phong",
    title: "Bảo trì phòng ngừa tòa nhà: Lịch trình và ngân sách",
    excerpt: "Cách xây dựng kế hoạch bảo trì phòng ngừa (preventive maintenance) giúp kéo dài tuổi thọ và giảm chi phí sự cố.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Lê Văn C",
    date: "2025-02-15",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["quản lý tòa nhà", "bảo trì"],
  },
  {
    id: 41,
    slug: "an-ninh-toa-nha-van-phong",
    title: "An ninh tòa nhà văn phòng: Mô hình vận hành 24/7",
    excerpt: "Mô hình tổ chức an ninh cho tòa nhà văn phòng hạng A: nhân sự, công nghệ và quy trình ứng phó sự cố.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Hoàng Văn E",
    date: "2025-02-20",
    readTime: "10 phút",
    image: "/seo.png",
    tags: ["quản lý tòa nhà", "an ninh"],
  },
  // ===== Quản lý và Vận hành — Quản lý tài sản =====
  {
    id: 42,
    slug: "quan-ly-tai-san-bds-tong-quan",
    title: "Quản lý tài sản BĐS: Từ chiến lược đến thực thi",
    excerpt: "Tổng quan về asset management trong BĐS — lập chiến lược, phân bổ nguồn lực và đo lường hiệu quả danh mục.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Nguyễn Văn A",
    date: "2025-02-25",
    readTime: "12 phút",
    image: "/seo.png",
    featured: true,
    tags: ["quản lý tài sản", "chiến lược"],
  },
  {
    id: 43,
    slug: "toi-uu-hieu-suat-tai-san-cho-thue",
    title: "Tối ưu hiệu suất tài sản cho thuê: KPI cần theo dõi",
    excerpt: "Occupancy, NOI, yield — các chỉ số then chốt để đánh giá và tối ưu hiệu suất một tài sản BĐS cho thuê.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Phạm Thị D",
    date: "2025-03-02",
    readTime: "9 phút",
    image: "/seo.png",
    tags: ["quản lý tài sản", "KPI"],
  },
  {
    id: 44,
    slug: "vong-doi-tai-san-bds",
    title: "Vòng đời tài sản BĐS: Giai đoạn nào tạo giá trị lớn nhất?",
    excerpt: "Phân tích 4 giai đoạn vòng đời tài sản (acquisition, operation, optimization, disposition) và giá trị tạo ra ở mỗi giai đoạn.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Vũ Thị F",
    date: "2025-03-08",
    readTime: "11 phút",
    image: "/seo.png",
    tags: ["quản lý tài sản", "vòng đời"],
  },
  {
    id: 45,
    slug: "cap-nhat-tai-san-tang-gia-tri",
    title: "Nâng cấp tài sản BĐS: Khi nào và bao nhiêu là đủ?",
    excerpt: "Khung đánh giá ROI cho các khoản đầu tư nâng cấp tài sản — từ retrofit hệ thống đến repositioning toàn tòa.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Đặng Văn G",
    date: "2025-03-12",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["quản lý tài sản", "nâng cấp"],
  },
  // ===== Quản lý và Vận hành — Facility & Operation =====
  {
    id: 46,
    slug: "facility-management-tieu-chuan-quoc-te",
    title: "Facility Management theo tiêu chuẩn quốc tế: ISO 41001 thực hành",
    excerpt: "Tổng quan ISO 41001 và cách áp dụng hệ thống quản lý facility tại các tòa nhà thương mại Việt Nam.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Lê Văn C",
    date: "2025-03-18",
    readTime: "13 phút",
    image: "/seo.png",
    featured: true,
    tags: ["facility & operation", "ISO 41001"],
  },
  {
    id: 47,
    slug: "kpi-facility-management",
    title: "12 KPI Facility Management mỗi quản lý tòa nhà cần biết",
    excerpt: "Bộ KPI vận hành: SLA, MTTR, energy intensity, satisfaction score — định nghĩa, công thức và benchmark.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Hoàng Văn E",
    date: "2025-03-22",
    readTime: "10 phút",
    image: "/seo.png",
    tags: ["facility & operation", "KPI"],
  },
  {
    id: 48,
    slug: "esg-van-hanh-toa-nha-xanh",
    title: "ESG trong vận hành tòa nhà: Từ cam kết đến số liệu",
    excerpt: "Cách đo lường và báo cáo ESG cho tòa nhà — energy, waste, water, social và governance trong vận hành hàng ngày.",
    category: "Quản lý và Vận hành",
    categorySlug: "quan-ly-van-hanh",
    author: "Phạm Thị D",
    date: "2025-03-28",
    readTime: "12 phút",
    image: "/seo.png",
    tags: ["facility & operation", "ESG"],
  },
  // ===== Kiến trúc - Xây dựng — Thiết kế =====
  {
    id: 49,
    slug: "thiet-ke-noi-that-ben-vung",
    title: "Thiết kế nội thất bền vững: Xu hướng xanh 2025",
    excerpt: "Các giải pháp thiết kế nội thất thân thiện với môi trường đang dẫn đầu xu hướng năm 2025.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Đặng Văn G",
    date: "2024-12-28",
    readTime: "6 phút",
    image: "/seo.png",
    featured: true,
    tags: ["thiết kế", "bền vững"],
  },
  {
    id: 50,
    slug: "thiet-ke-kien-truc-toa-nha-van-phong",
    title: "Thiết kế kiến trúc tòa nhà văn phòng hạng A: Tiêu chuẩn & xu hướng",
    excerpt: "Các nguyên tắc thiết kế văn phòng hạng A: tỷ lệ không gian, ánh sáng tự nhiên, tầng lõi và linh hoạt.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Đặng Văn G",
    date: "2025-02-05",
    readTime: "10 phút",
    image: "/seo.png",
    tags: ["thiết kế", "văn phòng"],
  },
  {
    id: 51,
    slug: "thiet-ke-can-ho-chuc-nang-nho",
    title: "Thiết kế căn hộ chức năng diện tích nhỏ: 10 nguyên tắc",
    excerpt: "Giải pháp tối ưu không gian cho căn hộ dưới 50m² — từ lưu trữ ẩn đến vách ngăn đa năng.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Vũ Thị F",
    date: "2025-02-12",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["thiết kế", "căn hộ"],
  },
  {
    id: 52,
    slug: "thiet-ke-concept-khach-san-resort",
    title: "Thiết kế concept khách sạn & resort: Kể chuyện qua không gian",
    excerpt: "Cách xây dựng concept thiết kế cho khách sạn/resort — từ narrative đến material palette và lighting.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Lê Văn C",
    date: "2025-02-18",
    readTime: "11 phút",
    image: "/seo.png",
    tags: ["thiết kế", "khách sạn"],
  },
  // ===== Kiến trúc - Xây dựng — Thi công =====
  {
    id: 53,
    slug: "quan-ly-giam-sat-thi-cong-tinh",
    title: "Quản lý & giám sát thi công tinh: Quy trình và công cụ",
    excerpt: "Quy trình giám sát thi công hiện đại — BIM, drone, photo log hàng ngày và checklist chất lượng.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Hoàng Văn E",
    date: "2025-02-22",
    readTime: "12 phút",
    image: "/seo.png",
    featured: true,
    tags: ["thi công", "giám sát"],
  },
  {
    id: 54,
    slug: "an-toan-lao-dong-cong-truong",
    title: "An toàn lao động công trường: Hệ thống quản lý HSE",
    excerpt: "Khung HSE cho công trường xây dựng — đánh giá rủi ro, training, PPE và quy trình ứng phó sự cố.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Trần Thị B",
    date: "2025-02-26",
    readTime: "9 phút",
    image: "/seo.png",
    tags: ["thi công", "an toàn"],
  },
  {
    id: 55,
    slug: "kiem-soat-chat-luong-thi-cong",
    title: "Kiểm soát chất lượng thi công: Từ vật liệu đến nghiệm thu",
    excerpt: "Quy trình QA/QC trong thi công — kiểm tra vật liệu đầu vào, kiểm soát công nghệ và nghiệm thu từng giai đoạn.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Nguyễn Văn A",
    date: "2025-03-04",
    readTime: "10 phút",
    image: "/seo.png",
    tags: ["thi công", "chất lượng"],
  },
  {
    id: 56,
    slug: "quan-ly-tien-do-thi-cong-bim",
    title: "Quản lý tiến độ thi công bằng BIM 4D: Thực hành",
    excerpt: "Ứng dụng BIM 4D để lập lịch và kiểm soát tiến độ thi công — case study dự án thương mại lớn.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Đặng Văn G",
    date: "2025-03-10",
    readTime: "13 phút",
    image: "/seo.png",
    tags: ["thi công", "BIM"],
  },
  // ===== Kiến trúc - Xây dựng — Cải tạo công trình =====
  {
    id: 57,
    slug: "cai-tao-toa-nha-van-phong-co",
    title: "Cải tạo tòa nhà văn phòng cũ: Từ retrofit đến repositioning",
    excerpt: "Cải tạo nâng hạng tòa nhà văn phòng cũ — hệ thống MEP, facade, lobby và tối ưu hiệu suất cho thuê.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Phạm Thị D",
    date: "2025-03-15",
    readTime: "11 phút",
    image: "/seo.png",
    featured: true,
    tags: ["cải tạo", "văn phòng"],
  },
  {
    id: 58,
    slug: "cai-tao-can-ho-cu-chuyen-moi",
    title: "Cải tạo căn hộ cũ thành không gian hiện đại: Chi phí & giá trị",
    excerpt: "Đánh giá ROI khi cải tạo căn hộ cũ — ngân sách, hạng mục ưu tiên và giá trị gia tăng khi bán/cho thuê.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Vũ Thị F",
    date: "2025-03-20",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["cải tạo", "căn hộ"],
  },
  {
    id: 59,
    slug: "cai-tao-cong-trinh-cong-cong",
    title: "Cải tạo công trình công cộng: Tiêu chuẩn tiếp cận & thẩm mỹ",
    excerpt: "Cải tạo công trình công cộng — accessibility, bảo tồn và nâng cấp thẩm mỹ trong ngân sách hạn hẹp.",
    category: "Kiến trúc - Xây dựng",
    categorySlug: "kien-truc-xay-dung",
    author: "Lê Văn C",
    date: "2025-03-25",
    readTime: "10 phút",
    image: "/seo.png",
    tags: ["cải tạo", "công cộng"],
  },
  // ===== Hoạt động Kepler — Tin doanh nghiệp =====
  {
    id: 60,
    slug: "kepler-ky-niem-5-nam",
    title: "Kepler Group kỷ niệm 5 năm thành lập: Hành trình phát triển",
    excerpt: "Nhìn lại 5 năm phát triển của Kepler Group với những cột mốc quan trọng và định hướng tương lai.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban truyền thông",
    date: "2024-12-25",
    readTime: "5 phút",
    image: "/seo.png",
    featured: true,
    tags: ["tin doanh nghiệp", "kỷ niệm"],
  },
  {
    id: 61,
    slug: "kepler-bao-cao-ket-qua-2024",
    title: "Kepler công bố báo cáo kết quả hoạt động 2024",
    excerpt: "Tổng kết năm 2024: doanh thu tăng trưởng, mở rộng danh mục khách hàng và định hướng 2025.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban truyền thông",
    date: "2025-01-10",
    readTime: "6 phút",
    image: "/seo.png",
    tags: ["tin doanh nghiệp", "báo cáo"],
  },
  {
    id: 62,
    slug: "kepler-mo-ranh-vuc-consulting",
    title: "Kepler mở rộng mảng consulting chuyển đổi số BĐS",
    excerpt: "Đơn vị consulting chuyển đổi số chính thức ra mắt, bổ sung hệ sinh thái dịch vụ Kepler Group.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban truyền thông",
    date: "2025-01-20",
    readTime: "4 phút",
    image: "/seo.png",
    tags: ["tin doanh nghiệp", "mở rộng"],
  },
  {
    id: 63,
    slug: "kepler-nhan-chung-chi-iso",
    title: "Kepler đạt chứng nhận ISO 9001:2015 cho quy trình thẩm định giá",
    excerpt: "Hệ thống quản lý chất lượng Kepler được công nhận quốc tế, nâng cao niềm tin của khách hàng và đối tác.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban truyền thông",
    date: "2025-02-01",
    readTime: "5 phút",
    image: "/seo.png",
    tags: ["tin doanh nghiệp", "chứng nhận"],
  },
  // ===== Hoạt động Kepler — Sự kiện =====
  {
    id: 64,
    slug: "kepler-to-chuc-le-ra-mat-bao-cao-2025",
    title: "Kepler tổ chức lễ ra mắt báo cáo thị trường BĐS 2025",
    excerpt: "Sự kiện ra mắt báo cáo thường niên thu hút 200+ khách mời từ giới đầu tư và phát triển dự án.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban sự kiện",
    date: "2025-02-12",
    readTime: "7 phút",
    image: "/seo.png",
    featured: true,
    tags: ["sự kiện", "ra mắt"],
  },
  {
    id: 65,
    slug: "kepler-tham-gia-vietbuild-2025",
    title: "Kepler tham gia triển lãm Vietbuild 2025: Booth & hoạt động",
    excerpt: "Hình ảnh và hoạt động nổi bật của Kepler tại Vietbuild 2025 — gặp gỡ đối tác và khách hàng.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban sự kiện",
    date: "2025-02-18",
    readTime: "6 phút",
    image: "/seo.png",
    tags: ["sự kiện", "triển lãm"],
  },
  {
    id: 66,
    slug: "kepler-to-chuc-workshop-esg",
    title: "Workshop ESG trong BĐS: Kepler đồng tổ chức cùng đối tác",
    excerpt: "Workshop ESG cho doanh nghiệp BĐS — chia sẻ khung thực hành và case study từ thị trường Việt Nam.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban sự kiện",
    date: "2025-02-25",
    readTime: "8 phút",
    image: "/seo.png",
    tags: ["sự kiện", "workshop"],
  },
  {
    id: 67,
    slug: "kepler-gala-dinner-2025",
    title: "Kepler Gala Dinner 2025: Tôn vinh và tri ân đối tác",
    excerpt: "Đêm gala tri ân khách hàng và đối tác — nhìn lại hành trình và chia sẻ tầm nhìn 2025-2030.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban sự kiện",
    date: "2025-03-01",
    readTime: "5 phút",
    image: "/seo.png",
    tags: ["sự kiện", "gala"],
  },
  // ===== Hoạt động Kepler — Nội bộ & hợp tác =====
  {
    id: 68,
    slug: "kepler-ky-ket-hop-tac-ngan-hang",
    title: "Kepler ký kết hợp tác chiến lược với ngân hàng lớn",
    excerpt: "Thỏa thuận hợp tác cung cấp dịch vụ thẩm định giá và tư vấn tài sản cho khách hàng doanh nghiệp.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban hợp tác",
    date: "2025-03-08",
    readTime: "6 phút",
    image: "/seo.png",
    featured: true,
    tags: ["nội bộ & hợp tác", "ngân hàng"],
  },
  {
    id: 69,
    slug: "kepler-noi-bo-training-2025",
    title: "Chương trình đào tạo nội bộ Kepler 2025: Nâng tầm chuyên môn",
    excerpt: "Lộ trình đào tạo 2025 cho nhân sự Kepler — kỹ năng chuyên môn, quản lý và chứng chỉ quốc tế.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban nhân sự",
    date: "2025-03-15",
    readTime: "7 phút",
    image: "/seo.png",
    tags: ["nội bộ & hợp tác", "đào tạo"],
  },
  {
    id: 70,
    slug: "kepler-hop-tac-dai-hoc",
    title: "Kepler hợp tác với đại học: Chương trình thực tập & nghiên cứu",
    excerpt: "Chương trình hợp tác đào tạo — thực tập sinh, nghiên cứu chung và học bổng Kepler cho sinh viên.",
    category: "Hoạt động Kepler",
    categorySlug: "hoat-dong-kepler",
    author: "Ban hợp tác",
    date: "2025-03-22",
    readTime: "6 phút",
    image: "/seo.png",
    tags: ["nội bộ & hợp tác", "đại học"],
  },
];

// Video mock
export const VIDEOS: VideoItem[] = [
  {
    id: 1,
    slug: "webinar-phan-tich-thi-truong-bds-2025",
    title: "Webinar: Phân tích thị trường BĐS 2025",
    description: "Chuyên gia Kepler phân tích xu hướng và cơ hội đầu tư BĐS năm 2025.",
    duration: "45:30",
    thumbnail: "/seo.png",
    date: "2025-01-15",
    views: "1.2K",
    category: "Webinar",
    tags: ["thị trường", "2025"],
  },
  {
    id: 2,
    slug: "huong-dan-tham-dinh-gia-bds-thuong-mai",
    title: "Hướng dẫn thẩm định giá BĐS thương mại",
    description: "Video hướng dẫn phương pháp thẩm định giá BĐS thương mại thực tế.",
    duration: "32:15",
    thumbnail: "/seo.png",
    date: "2025-01-10",
    views: "856",
    category: "Hướng dẫn",
    tags: ["thẩm định giá"],
  },
  {
    id: 3,
    slug: "kepler-talk-khoi-nghiep-nganh-bds",
    title: "Kepler Talk: Câu chuyện khởi nghiệp trong ngành BĐS",
    description: "Đối thoại với lãnh đạo Kepler về hành trình xây dựng doanh nghiệp.",
    duration: "28:40",
    thumbnail: "/seo.png",
    date: "2025-01-05",
    views: "2.1K",
    category: "Kepler Talk",
    tags: ["khởi nghiệp"],
  },
  {
    id: 4,
    slug: "tour-ao-du-an-can-ho-cao-cap",
    title: "Tour ảo: Dự án căn hộ cao cấp mới",
    description: "Khám phá dự án căn hộ cao cấp với công nghệ VR 360 độ.",
    duration: "15:20",
    thumbnail: "/seo.png",
    date: "2024-12-28",
    views: "3.5K",
    category: "Tour ảo",
    tags: ["căn hộ", "VR"],
  },
  {
    id: 5,
    slug: "phan-tich-quy-hoach-tp-hcm-2025",
    title: "Phân tích quy hoạch TP.HCM 2025",
    description: "Video phân tích chi tiết các thay đổi quy hoạch tại TP.HCM.",
    duration: "38:50",
    thumbnail: "/seo.png",
    date: "2024-12-20",
    views: "1.8K",
    category: "Phân tích",
    tags: ["quy hoạch", "TP.HCM"],
  },
  {
    id: 6,
    slug: "huong-dan-dau-tu-bds-cong-nghiep",
    title: "Hướng dẫn đầu tư BĐS công nghiệp",
    description: "Chuyên gia chia sẻ kinh nghiệm đầu tư BĐS công nghiệp hiệu quả.",
    duration: "22:10",
    thumbnail: "/seo.png",
    date: "2024-12-15",
    views: "967",
    category: "Hướng dẫn",
    tags: ["đầu tư", "công nghiệp"],
  },
  {
    id: 7,
    slug: "webinar-dau-tu-bds-cong-nghiep-2025",
    title: "Webinar: Đầu tư BĐS công nghiệp — Cơ hội 2025",
    description: "Webinar phân tích cơ hội đầu tư BĐS công nghiệp và chiến lược phân bổ vốn.",
    duration: "52:00",
    thumbnail: "/seo.png",
    date: "2025-02-10",
    views: "1.5K",
    category: "Webinar",
    tags: ["đầu tư", "công nghiệp"],
  },
  {
    id: 8,
    slug: "kepler-talk-esg-trong-bds",
    title: "Kepler Talk: ESG trong bất động sản",
    description: "Đối thoại với chuyên gia ESG về xu hướng đầu tư bền vững trong BĐS.",
    duration: "35:20",
    thumbnail: "/seo.png",
    date: "2025-02-05",
    views: "1.3K",
    category: "Kepler Talk",
    tags: ["ESG", "bền vững"],
  },
  {
    id: 9,
    slug: "tour-ao-van-phong-hang-a",
    title: "Tour ảo: Tòa nhà văn phòng hạng A mới",
    description: "Khám phá tòa nhà văn phòng hạng A với thiết kế hiện đại và tiện ích cao cấp.",
    duration: "18:45",
    thumbnail: "/seo.png",
    date: "2025-01-28",
    views: "2.8K",
    category: "Tour ảo",
    tags: ["văn phòng"],
  },
  {
    id: 10,
    slug: "phan-tich-thi-truong-bds-q1-2025",
    title: "Phân tích thị trường BĐS Quý 1/2025",
    description: "Video phân tích diễn biến thị trường BĐS quý 1/2025 và dự báo quý 2.",
    duration: "42:15",
    thumbnail: "/seo.png",
    date: "2025-02-18",
    views: "1.1K",
    category: "Phân tích",
    tags: ["thị trường", "quý 1"],
  },
  {
    id: 11,
    slug: "huong-dan-quan-ly-toa-nha-thong-minh",
    title: "Hướng dẫn quản lý tòa nhà thông minh với IoT",
    description: "Video hướng dẫn ứng dụng IoT trong quản lý vận hành tòa nhà.",
    duration: "25:30",
    thumbnail: "/seo.png",
    date: "2025-02-22",
    views: "743",
    category: "Hướng dẫn",
    tags: ["quản lý tòa nhà", "IoT"],
  },
  {
    id: 12,
    slug: "kepler-talk-ma-trong-bds",
    title: "Kepler Talk: M&A trong bất động sản",
    description: "Đối thoại về các giao dịch M&A nổi bật và cơ hội cho nhà đầu tư.",
    duration: "40:10",
    thumbnail: "/seo.png",
    date: "2025-02-25",
    views: "1.9K",
    category: "Kepler Talk",
    tags: ["M&A"],
  },
];

// Podcast mock
export const PODCASTS: PodcastItem[] = [
  {
    id: 1,
    slug: "kepler-podcast-12-tuong-lai-bds-thong-minh",
    title: "Kepler Podcast #12: Tương lai của BĐS thông minh",
    description: "Thảo luận về xu hướng BĐS thông minh và công nghệ prop-tech.",
    duration: "52:30",
    episode: 12,
    date: "2025-01-15",
    guests: "TS. Nguyễn Văn A",
    category: "Công nghệ",
    tags: ["prop-tech", "BĐS thông minh"],
  },
  {
    id: 2,
    slug: "kepler-podcast-11-dau-tu-bds-boi-canh-moi",
    title: "Kepler Podcast #11: Đầu tư BĐS trong bối cảnh kinh tế mới",
    description: "Phân tích cơ hội đầu tư BĐS trong bối cảnh kinh tế vĩ mô 2025.",
    duration: "45:15",
    episode: 11,
    date: "2025-01-08",
    guests: "Ông Trần B, CEO quỹ đầu tư",
    category: "Đầu tư",
    tags: ["đầu tư", "vĩ mô"],
  },
  {
    id: 3,
    slug: "kepler-podcast-10-quan-ly-toa-nha-ben-vung",
    title: "Kepler Podcast #10: Quản lý tòa nhà bền vững",
    description: "Chuyên gia chia sẻ về quản lý tòa nhà xanh và bền vững.",
    duration: "38:20",
    episode: 10,
    date: "2024-12-30",
    guests: "Bà Lê C, chuyên gia ESG",
    category: "Vận hành",
    tags: ["ESG", "bền vững"],
  },
  {
    id: 4,
    slug: "kepler-podcast-9-phap-ly-bds",
    title: "Kepler Podcast #9: Pháp lý BĐS - Những điều cần biết",
    description: "Luật sư chia sẻ các vấn đề pháp lý thường gặp trong giao dịch BĐS.",
    duration: "41:10",
    episode: 9,
    date: "2024-12-22",
    guests: "LS. Phạm D",
    category: "Pháp lý",
    tags: ["pháp lý"],
  },
  {
    id: 5,
    slug: "kepler-podcast-8-tham-dinh-gia-tai-chinh",
    title: "Kepler Podcast #8: Thẩm định giá và tài chính dự án",
    description: "Đối thoại về thẩm định giá và tài chính dự án BĐS.",
    duration: "48:45",
    episode: 8,
    date: "2024-12-15",
    guests: "Ông Hoàng E, chuyên gia tài chính",
    category: "Tài chính",
    tags: ["thẩm định giá", "tài chính"],
  },
  {
    id: 6,
    slug: "kepler-podcast-7-kien-truc-xanh",
    title: "Kepler Podcast #7: Kiến trúc xanh và thiết kế bền vững",
    description: "Kiến trúc sư chia sẻ về xu hướng thiết kế xanh và chứng nhận LEED.",
    duration: "44:00",
    episode: 7,
    date: "2024-12-08",
    guests: "KTS. Đặng G",
    category: "Kiến trúc",
    tags: ["kiến trúc", "LEED"],
  },
  {
    id: 7,
    slug: "kepler-podcast-6-quy-hoach-tp-hcm",
    title: "Kepler Podcast #6: Quy hoạch TP.HCM — Cơ hội và thách thức",
    description: "Phân tích quy hoạch TP.HCM và tác động đến thị trường BĐS.",
    duration: "55:20",
    episode: 6,
    date: "2024-12-01",
    guests: "TS. Nguyễn Văn A",
    category: "Quy hoạch",
    tags: ["quy hoạch", "TP.HCM"],
  },
  {
    id: 8,
    slug: "kepler-podcast-5-ma-trong-bds",
    title: "Kepler Podcast #5: M&A trong bất động sản",
    description: "Đối thoại về các giao dịch M&A nổi bật và chiến lược tích hợp.",
    duration: "50:10",
    episode: 5,
    date: "2024-11-24",
    guests: "Ông Trần B",
    category: "Đầu tư",
    tags: ["M&A"],
  },
  {
    id: 9,
    slug: "kepler-podcast-4-chuyen-doi-so-bds",
    title: "Kepler Podcast #4: Chuyển đổi số trong BĐS",
    description: "CIO chia sẻ hành trình chuyển đổi số tại doanh nghiệp BĐS.",
    duration: "42:30",
    episode: 4,
    date: "2024-11-17",
    guests: "Ông Phạm H, CIO",
    category: "Công nghệ",
    tags: ["chuyển đổi số"],
  },
  {
    id: 10,
    slug: "kepler-podcast-3-can-ho-thuong-mai",
    title: "Kepler Podcast #3: Thị trường căn hộ thương mại 2024",
    description: "Phân tích cung cầu và xu hướng thị trường căn hộ thương mại.",
    duration: "39:45",
    episode: 3,
    date: "2024-11-10",
    guests: "Bà Lê C",
    category: "Thị trường",
    tags: ["căn hộ", "thương mại"],
  },
  {
    id: 11,
    slug: "kepler-podcast-2-bds-cong-nghiep",
    title: "Kepler Podcast #2: Đầu tư BĐS công nghiệp — Cơ hội từ FDI",
    description: "Cơ hội đầu tư BĐS công nghiệp từ làn sóng FDI vào Việt Nam.",
    duration: "47:15",
    episode: 2,
    date: "2024-11-03",
    guests: "Ông Hoàng E",
    category: "Đầu tư",
    tags: ["BĐS công nghiệp", "FDI"],
  },
  {
    id: 12,
    slug: "kepler-podcast-1-khoi-nghiep-kepler",
    title: "Kepler Podcast #1: Hành trình khởi nghiệp Kepler",
    description: "Câu chuyện khởi nghiệp Kepler Group từ ngày đầu — đặc biệt pilot.",
    duration: "58:00",
    episode: 1,
    date: "2024-10-27",
    guests: "CEO Kepler Group",
    category: "Kepler Talk",
    tags: ["khởi nghiệp", "Kepler"],
  },
];

// Webinar mock
export const WEBINARS: WebinarItem[] = [
  {
    id: 1,
    slug: "webinar-du-bao-thi-truong-bds-2025",
    title: "Webinar: Dự báo thị trường BĐS 2025",
    description: "Webinar phân tích và dự báo thị trường BĐS năm 2025 với các chuyên gia hàng đầu.",
    date: "2025-02-15",
    time: "14:00 - 16:00",
    duration: "2 giờ",
    speaker: "TS. Nguyễn Văn A",
    status: "upcoming",
    registrationUrl: "#",
    category: "Thị trường",
    tags: ["dự báo", "2025"],
  },
  {
    id: 2,
    slug: "webinar-dau-tu-bds-cong-nghiep-2025",
    title: "Webinar: Đầu tư BĐS công nghiệp - Cơ hội 2025",
    description: "Tìm hiểu cơ hội đầu tư BĐS công nghiệp và chiến lược phân bổ vốn.",
    date: "2025-02-20",
    time: "10:00 - 11:30",
    duration: "1.5 giờ",
    speaker: "Ông Trần B",
    status: "upcoming",
    registrationUrl: "#",
    category: "Đầu tư",
    tags: ["BĐS công nghiệp"],
  },
  {
    id: 3,
    slug: "webinar-esg-trong-bds",
    title: "Webinar: ESG trong bất động sản",
    description: "Khung thực hành ESG cho doanh nghiệp BĐS — case study và benchmark.",
    date: "2025-03-05",
    time: "14:00 - 16:00",
    duration: "2 giờ",
    speaker: "Bà Lê C",
    status: "upcoming",
    registrationUrl: "#",
    category: "ESG",
    tags: ["ESG", "bền vững"],
  },
  {
    id: 4,
    slug: "webinar-tham-dinh-gia-bds-thuong-mai",
    title: "Webinar: Thẩm định giá BĐS thương mại",
    description: "Hướng dẫn thực hành thẩm định giá BĐS thương mại với case study thực tế.",
    date: "2025-01-10",
    time: "14:00 - 16:00",
    duration: "2 giờ",
    speaker: "Bà Lê C",
    status: "recorded",
    category: "Thẩm định giá",
    tags: ["thẩm định giá"],
  },
  {
    id: 5,
    slug: "webinar-phap-ly-bds-moi-nhat",
    title: "Webinar: Pháp lý BĐS mới nhất",
    description: "Cập nhật các quy định pháp lý BĐS mới nhất và ảnh hưởng đến giao dịch.",
    date: "2024-12-20",
    time: "10:00 - 11:30",
    duration: "1.5 giờ",
    speaker: "LS. Phạm D",
    status: "recorded",
    category: "Pháp lý",
    tags: ["pháp lý"],
  },
  {
    id: 6,
    slug: "webinar-quy-hoach-tp-hcm-2025",
    title: "Webinar: Quy hoạch TP.HCM 2025 — Khu vực tiềm năng",
    description: "Phân tích chi tiết thay đổi quy hoạch TP.HCM và cơ hội đầu tư.",
    date: "2024-12-10",
    time: "14:00 - 16:00",
    duration: "2 giờ",
    speaker: "TS. Nguyễn Văn A",
    status: "recorded",
    category: "Quy hoạch",
    tags: ["quy hoạch", "TP.HCM"],
  },
  {
    id: 7,
    slug: "webinar-chuyen-doi-so-doanh-nghiep-bds",
    title: "Webinar: Chuyển đổi số doanh nghiệp BĐS",
    description: "Hành trình chuyển đổi số — công cụ, quy trình và bài học thực tế.",
    date: "2024-11-28",
    time: "10:00 - 11:30",
    duration: "1.5 giờ",
    speaker: "Ông Phạm H",
    status: "recorded",
    category: "Công nghệ",
    tags: ["chuyển đổi số"],
  },
  {
    id: 8,
    slug: "webinar-ma-trong-bds",
    title: "Webinar: M&A trong BĐS — Chiến lược và thực thi",
    description: "Phân tích giao dịch M&A nổi bật và chiến lược tích hợp sau mua.",
    date: "2024-11-15",
    time: "14:00 - 16:00",
    duration: "2 giờ",
    speaker: "Ông Trần B",
    status: "recorded",
    category: "Đầu tư",
    tags: ["M&A"],
  },
];

// FAQ mock
export const FAQS: FAQItem[] = [
  {
    id: 1,
    group: "Thẩm định giá",
    question: "Thẩm định giá tài sản là gì?",
    answer: "Thẩm định giá tài sản là quá trình xác định giá trị của tài sản bằng các phương pháp chuyên nghiệp, tuân thủ tiêu chuẩn quốc tế và quy định pháp lý Việt Nam, nhằm cung cấp cơ sở cho các quyết định tài chính, pháp lý và đầu tư.",
  },
  {
    id: 2,
    group: "Thẩm định giá",
    question: "Thời gian thẩm định giá một tài sản mất bao lâu?",
    answer: "Thời gian thẩm định phụ thuộc vào loại tài sản và quy mô. Thông thường, thẩm định BĐS dân dụng mất 3-5 ngày làm việc, BĐS thương mại 5-10 ngày, và các dự án phức tạp có thể mất 2-4 tuần.",
  },
  {
    id: 3,
    group: "Thẩm định giá",
    question: "Chi phí thẩm định giá được tính như thế nào?",
    answer: "Chi phí thẩm định giá được tính dựa trên loại tài sản, quy mô, độ phức tạp và mục đích thẩm định. Kepler cung cấp báo giá chi tiết sau khi tiếp nhận thông tin yêu cầu từ khách hàng.",
  },
  {
    id: 4,
    group: "Môi giới BĐS",
    question: "Kepler cung cấp dịch vụ môi giới cho loại BĐS nào?",
    answer: "Kepler cung cấp dịch vụ môi giới cho đa dạng loại BĐS: căn hộ, nhà phố, biệt thự, BĐS thương mại (văn phòng, trung tâm thương mại), BĐS công nghiệp (nhà xưởng, kho bãi, đất nền khu công nghiệp).",
  },
  {
    id: 5,
    group: "Môi giới BĐS",
    question: "Hoa hồng môi giới được tính như thế nào?",
    answer: "Hoa hồng môi giới được tính theo tỷ lệ phần trăm trên giá trị giao dịch hoặc theo thỏa thuận giữa các bên. Mức phí cụ thể phụ thuộc vào loại BĐS, giá trị giao dịch và phạm vi dịch vụ.",
  },
  {
    id: 6,
    group: "Quản lý vận hành",
    question: "Dịch vụ quản lý tòa nhà của Kepler bao gồm những gì?",
    answer: "Dịch vụ quản lý tòa nhà bao gồm: quản lý kỹ thuật, quản lý an ninh, quản lý vệ sinh, quản lý tài chính, quản lý khách thuê, và dịch vụ chăm sóc khách hàng. Kepler áp dụng tiêu chuẩn quốc tế trong vận hành.",
  },
  {
    id: 7,
    group: "Quản lý vận hành",
    question: "Có thể thuê quản lý vận hành cho tòa nhà đang hoạt động không?",
    answer: "Có. Kepler tiếp nhận quản lý vận hành cho tòa nhà đang hoạt động. Quy trình tiếp nhận bao gồm đánh giá hiện trạng, lập kế hoạch chuyển giao, và triển khai dịch vụ theo tiêu chuẩn Kepler.",
  },
  {
    id: 8,
    group: "Tư vấn M&A",
    question: "Kepler hỗ trợ M&A trong những lĩnh vực nào?",
    answer: "Kepler hỗ trợ M&A trong lĩnh vực BĐS và các ngành liên quan: sáp nhập doanh nghiệp, mua bán dự án, gọi vốn, tái cấu trúc. Dịch vụ bao gồm phân tích chiến lược, định giá, đàm phán và hoàn tất giao dịch.",
  },
  {
    id: 9,
    group: "Tư vấn M&A",
    question: "Quy trình M&A tại Kepler mất bao lâu?",
    answer: "Quy trình M&A phụ thuộc vào quy mô và độ phức tạp của giao dịch. Thông thường, từ phân tích ban đầu đến hoàn tất giao dịch mất 3-6 tháng, các giao dịch phức tạp có thể mất 6-12 tháng.",
  },
  {
    id: 10,
    group: "Marketing BĐS",
    question: "Dịch vụ marketing BĐS của Kepler bao gồm những gì?",
    answer: "Dịch vụ marketing BĐS bao gồm: chiến lược positioning, digital marketing, sự kiện ra mắt, content marketing, branding dự án, và phân tích hiệu quả chiến dịch. Kepler tích hợp marketing với bán hàng để tối ưu chuyển đổi.",
  },
  {
    id: 11,
    group: "Nội thất",
    question: "Kepler có cung cấp dịch vụ thiết kế nội thất không?",
    answer: "Có. Kepler cung cấp dịch vụ thiết kế và hoàn thiện nội thất cho căn hộ, văn phòng, khách sạn và các dự án thương mại. Dịch vụ bao gồm thiết kế concept, thi công và bảo hành.",
  },
  {
    id: 12,
    group: "Nội thất",
    question: "Thời gian thi công nội thất mất bao lâu?",
    answer: "Thời gian thi công phụ thuộc vào quy mô và độ phức tạp. Căn hộ thông thường 2-3 tháng, văn phòng 1-2 tháng, dự án lớn 3-6 tháng. Kepler cam kết tiến độ và chất lượng theo hợp đồng.",
  },
];

// Báo cáo/tài liệu tải xuống mock
export const REPORTS: ReportItem[] = [
  {
    id: 1,
    title: "Báo cáo thị trường BĐS Quý 4/2024",
    description: "Tổng kết thị trường BĐS quý 4/2024 và dự báo 2025",
    fileType: "PDF",
    fileSize: "2.4 MB",
    date: "2024-12-20",
    category: "Thị trường",
    fileUrl: "/files/bao-cao-thi-truong-bds-q4-2024.pdf",
  },
  {
    id: 2,
    title: "Báo cáo phân tích BĐS công nghiệp 2024",
    description: "Phân tích chi tiết thị trường BĐS công nghiệp Việt Nam",
    fileType: "PDF",
    fileSize: "3.1 MB",
    date: "2024-11-15",
    category: "Đầu tư",
    fileUrl: "/files/bao-cao-bds-cong-nghiep-2024.pdf",
  },
  {
    id: 3,
    title: "Hướng dẫn thẩm định giá BĐS thương mại",
    description: "Tài liệu hướng dẫn phương pháp thẩm định giá BĐS thương mại",
    fileType: "PDF",
    fileSize: "1.8 MB",
    date: "2024-10-30",
    category: "Thẩm định giá",
    fileUrl: "/files/huong-dan-tham-dinh-gia-bds-thuong-mai.pdf",
  },
  {
    id: 4,
    title: "Cập nhật pháp lý BĐS 2024",
    description: "Tổng hợp các thay đổi pháp lý BĐS trong năm 2024",
    fileType: "PDF",
    fileSize: "1.2 MB",
    date: "2024-12-01",
    category: "Pháp lý",
    fileUrl: "/files/cap-nhat-phap-ly-bds-2024.pdf",
  },
];

// Dữ liệu khu vực — quy hoạch theo vùng
export const REGIONS: RegionItem[] = [
  {
    id: 1,
    name: "TP. Hồ Chí Minh",
    code: "SGN",
    area: "2.095 km²",
    population: "9.3 triệu",
    planningStatus: "Đã phê duyệt",
    highlights: [
      "Quy hoạch chung 2035, tầm nhìn 2050",
      "Phát triển 6 vùng động lực",
      "Hạ tầng Metro tuyến 1 & 2",
    ],
    lastUpdate: "2024-11-30",
    keyProjects: 24,
  },
  {
    id: 2,
    name: "Hà Nội",
    code: "HAN",
    area: "3.359 km²",
    population: "8.5 triệu",
    planningStatus: "Đã phê duyệt",
    highlights: [
      "Quy hoạch vùng thủ đô 2030",
      "5 vành đai + 9 trục phương vị",
      "Chuyển dịch ra phía Tây & Nam",
    ],
    lastUpdate: "2024-10-15",
    keyProjects: 19,
  },
  {
    id: 3,
    name: "Đà Nẵng",
    code: "DAD",
    area: "1.285 km²",
    population: "1.2 triệu",
    planningStatus: "Đã phê duyệt",
    highlights: [
      "Đô thị thông minh & sinh thái 2030",
      "Cụm công nghệ cao Hoà Nhơn",
      "Phát triển du lịch bền vững",
    ],
    lastUpdate: "2024-09-22",
    keyProjects: 12,
  },
  {
    id: 4,
    name: "Bình Dương",
    code: "BDI",
    area: "2.695 km²",
    population: "2.5 triệu",
    planningStatus: "Đang lập",
    highlights: [
      "Quy hoạch tỉnh 2021-2030",
      "Khu đô thị thông minh mới",
      "Cụm công nghiệp công nghệ cao",
    ],
    lastUpdate: "2024-12-05",
    keyProjects: 16,
  },
  {
    id: 5,
    name: "Đồng Nai",
    code: "DNA",
    area: "5.907 km²",
    population: "3.1 triệu",
    planningStatus: "Chờ duyệt",
    highlights: [
      "Quy hoạch tỉnh 2021-2030",
      "Sân bay Long Thành",
      "Hành lang kinh tế Đông - Tây",
    ],
    lastUpdate: "2024-08-18",
    keyProjects: 14,
  },
  {
    id: 6,
    name: "Hải Phòng",
    code: "HPH",
    area: "1.561 km²",
    population: "2.0 triệu",
    planningStatus: "Đã phê duyệt",
    highlights: [
      "Đô thị loại đặc biệt 2030",
      "Cảng biển nước sâu Lạch Huyện",
      "Cụm công nghiệp trọng điểm",
    ],
    lastUpdate: "2024-07-10",
    keyProjects: 11,
  },
];

// Helper functions
export function getArticlesByCategory(categorySlug: string): Article[] {
  return ARTICLES.filter((a) => a.categorySlug === categorySlug);
}

export function getFeaturedArticles(): Article[] {
  return ARTICLES.filter((a) => a.featured);
}

export function getLatestArticles(limit = 6): Article[] {
  return [...ARTICLES]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, limit);
}

export function getArticleBySlug(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}

export function getRelatedArticles(article: Article, limit = 3): Article[] {
  return ARTICLES.filter(
    (a) => a.id !== article.id && a.categorySlug === article.categorySlug
  ).slice(0, limit);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function formatDate(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString("vi-VN", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
}

export function getVideoBySlug(slug: string): VideoItem | undefined {
  return VIDEOS.find((v) => v.slug === slug);
}

export function getRelatedVideos(video: VideoItem, limit = 3): VideoItem[] {
  return VIDEOS.filter(
    (v) => v.id !== video.id && v.category === video.category,
  ).slice(0, limit);
}

export function getVideoCategories(): string[] {
  return Array.from(new Set(VIDEOS.map((v) => v.category)));
}

export function getPodcastBySlug(slug: string): PodcastItem | undefined {
  return PODCASTS.find((p) => p.slug === slug);
}

export function getRelatedPodcasts(podcast: PodcastItem, limit = 3): PodcastItem[] {
  return PODCASTS.filter(
    (p) => p.id !== podcast.id && p.category === podcast.category,
  ).slice(0, limit);
}

export function getPodcastCategories(): string[] {
  return Array.from(new Set(PODCASTS.map((p) => p.category)));
}

export function getWebinarBySlug(slug: string): WebinarItem | undefined {
  return WEBINARS.find((w) => w.slug === slug);
}

export function getRelatedWebinars(webinar: WebinarItem, limit = 3): WebinarItem[] {
  return WEBINARS.filter(
    (w) => w.id !== webinar.id && w.category === webinar.category,
  ).slice(0, limit);
}

export function getWebinarCategories(): string[] {
  return Array.from(new Set(WEBINARS.map((w) => w.category)));
}
