import Link from "next/link";
import { ArrowRight, BarChart3, Building2, CheckCircle2, FileSearch, Handshake, Landmark, LineChart, PencilRuler, Settings2 } from "lucide-react";

const services = [
  [LineChart, "Tư vấn đầu tư", "Phân tích đầu tư, nghiên cứu khả thi, Due Diligence, cấu trúc vốn, gọi vốn và IPO.", ["Phân tích đầu tư", "Nghiên cứu khả thi", "Due Diligence", "Cấu trúc vốn", "Gọi vốn", "IPO"], "tu-van-dau-tu"],
  [FileSearch, "Thẩm định giá", "Thẩm định bất động sản, máy móc - thiết bị, doanh nghiệp, dự án và tài sản vô hình.", ["Bất động sản", "Máy móc - thiết bị", "Giá trị doanh nghiệp", "Dự án bất động sản", "Tài sản vô hình"], "tham-dinh-gia"],
  [Building2, "Phát triển dự án", "Từ nghiên cứu thị trường, Master Planning đến Product Strategy, Marketing và Sales.", ["Nghiên cứu thị trường", "Master Planning", "Product Strategy", "Business Plan"], "phat-trien-du-an"],
  [Settings2, "Quản lý bất động sản và tài sản", "Quản lý tòa nhà, tài sản, kỹ thuật, cộng đồng, bảo trì và vận hành.", ["Building Management", "Property Management", "Asset Management", "Operation"], "quan-ly-bat-dong-san"],
  [BarChart3, "Asset Enhancement", "Tăng giá trị tài sản thông qua tăng doanh thu, công suất và Repositioning.", ["Tăng giá trị tài sản", "Tăng doanh thu", "Tăng công suất", "Repositioning"], "asset-enhancement"],
  [Handshake, "Tư vấn M&A", "Tư vấn bên mua, bên bán xuyên suốt từ Valuation, Due Diligence đến Closing và hậu M&A.", ["Pitch Book và Teaser", "Valuation", "Target Scouting", "Negotiation"], "tu-van-ma"],
  [Landmark, "Môi giới và Leasing", "Môi giới và cho thuê Office, Retail, Industrial, Land, Project, Warehouse và Factory.", ["Office", "Retail", "Industrial", "Warehouse & Factory"], "moi-gioi-leasing"],
  [PencilRuler, "Thiết kế và xây dựng", "Thiết kế kiến trúc, nội thất, thi công, cải tạo và hoàn thiện nội - ngoại thất.", ["Kiến trúc", "Nội thất", "Thi công", "Cải tạo"], "thiet-ke-xay-dung"],
  [LineChart, "Giải pháp số", "Giới thiệu giải pháp PropTech và kết nối sang RealHub Platform.", ["PropTech", "Dữ liệu bất động sản", "RealHub Platform"], "giai-phap-so"],
] as const;

export default function ServicesPageView({ basePath }: { basePath: string }) {
  return <main className="min-h-screen bg-gray-50 text-gray-900">
    <section className="relative overflow-hidden bg-[url('/images/category-banner-investment.png')] bg-cover bg-center"><div className="absolute inset-0 bg-black/55" /><div className="relative mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><div className="max-w-3xl"><p className="mb-5 text-sm font-bold uppercase tracking-[0.2em] text-red-300">Kepler Group</p><h1 className="text-4xl font-bold leading-tight text-white sm:text-6xl">Dịch vụ chuyên môn</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">Giải pháp toàn diện cho bất động sản và doanh nghiệp, từ nghiên cứu đầu tư, thẩm định giá đến phát triển, vận hành và gia tăng giá trị tài sản.</p><div className="mt-8"><Link href="/contact" className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3.5 text-sm font-semibold text-white hover:bg-primary/90">Liên hệ chuyên gia <ArrowRight className="h-4 w-4" /></Link></div></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-16 lg:px-10 lg:py-24"><div className="mb-10 max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-primary">Dịch vụ nổi bật</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Năng lực xuyên suốt vòng đời tài sản</h2><p className="mt-4 leading-7 text-slate-600">Kết hợp chuyên gia đa ngành, dữ liệu thị trường và kinh nghiệm triển khai thực tế.</p></div><div className="mb-12 grid gap-5 md:grid-cols-3">{services.slice(0, 3).map(([Icon, title, description, , slug]) => <Link key={slug} href={`${basePath}/${slug}`} className="group rounded-2xl bg-gray-900 p-6 text-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10 text-red-300"><Icon className="h-5 w-5" /></div><ArrowRight className="h-5 w-5 text-white/50 group-hover:translate-x-1 group-hover:text-white" /></div><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{description}</p></Link>)}</div><p className="mb-5 text-sm font-bold uppercase tracking-[0.18em] text-primary">Danh mục dịch vụ</p><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{services.map(([Icon, title, description, items, slug]) => <Link key={slug} href={`${basePath}/${slug}`} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl"><div className="flex items-start justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#b4232f]/10 text-primary"><Icon className="h-6 w-6" /></div><ArrowRight className="h-5 w-5 text-slate-300 group-hover:translate-x-1 group-hover:text-primary" /></div><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 min-h-14 text-sm leading-6 text-slate-600">{description}</p><ul className="mt-5 space-y-2 border-t border-slate-100 pt-4">{items.map(item => <li key={item} className="flex items-center gap-2 text-sm text-slate-500"><CheckCircle2 className="h-4 w-4 shrink-0 text-primary" />{item}</li>)}</ul></Link>)}</div></section>
    <section className="bg-white py-16 lg:py-24"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="mb-10"><p className="text-sm font-bold uppercase tracking-[0.18em] text-primary">Dự án & Case Study</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Kinh nghiệm triển khai thực tế</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Khám phá các dự án, nội dung chuyên môn và góc nhìn thị trường liên quan đến từng nhóm dịch vụ.</p></div><Link href="/news" className="inline-flex items-center gap-2 rounded-full border border-primary px-6 py-3 text-sm font-semibold text-primary hover:bg-primary hover:text-white">Xem dự án và Case Study <ArrowRight className="h-4 w-4" /></Link></div></section>
    <section className="bg-gray-900 px-6 py-16 text-center text-white lg:px-10"><h2 className="text-3xl font-bold sm:text-4xl">Cùng Kepler kiến tạo giá trị</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-white/60">Chia sẻ nhu cầu để đội ngũ Kepler đề xuất hướng tiếp cận phù hợp.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-full bg-primary px-7 py-3.5 text-sm font-semibold hover:bg-primary/90">Liên hệ ngay <ArrowRight className="h-4 w-4" /></Link></section>
  </main>;
}
