/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from './category';

export type CategoryWithChildrenAllOfCategoriesItemAllOf = {
  /** Nested child categories */
  categories?: Category[];
};
