/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Logo } from './logo';

export type GetApiV10LogoId200AllOf = {
  responseData?: Logo;
};
