/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * pageSize, visit https://www.npmjs.com/package/sequelize-api-paginate for syntax
 */
export type PageSizeParameter = number;
