/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { QuotationStatus } from './quotationStatus';

export type PostApiV10QuotationStatus200AllOf = {
  responseData?: QuotationStatus;
};
