/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface RolePermissionMutate {
  /** Role ID */
  role_id: string;
  /** Permission ID */
  permission_id: string;
}
