/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export interface ServiceMutate {
  /**
   * Name of the service
   * @minLength 1
   * @maxLength 255
   */
  name: string;
}
