/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KOSMO Backend API
 * Generated API documentation
 * OpenAPI spec version: 1.0.0
 */

export type UserSessionDeviceInfo = { [key: string]: unknown };
